export const featuredPost = {
  title: "Mengenal Artificial Intelligence dalam Perspektif Islam",
  excerpt:
    "Bagaimana teknologi AI dapat dimanfaatkan sesuai dengan nilai-nilai Islam dan etika teknologi yang bertanggung jawab untuk kemajuan umat.",
  content:
    "Dalam era digitalisasi yang semakin pesat, teknologi Artificial Intelligence (AI) telah menjadi bagian integral dari kehidupan manusia. Sebagai umat Muslim, kita perlu memahami bagaimana mengimplementasikan dan memanfaatkan teknologi ini sesuai dengan nilai-nilai Islam...",
  author: "Ahmad Fauzi",
  authorRole: "AI Research Lead",
  date: "2024-03-15",
  readTime: "8 min read",
  category: "AI & Ethics",
  image: "/blog/ai-islam.jpg",
  views: 1240,
  featured: true,
};

export const allPosts = [
  {
    title: "Tutorial: Membangun Web App dengan Next.js 14",
    excerpt: "Panduan lengkap untuk membuat aplikasi web modern menggunakan Next.js 14 dengan App Router dan Tailwind CSS.",
    author: "Siti Nurhaliza",
    authorRole: "Frontend Developer",
    date: "2024-03-12",
    readTime: "12 min read",
    category: "Web Development",
    image: "/blog/nextjs-tutorial.jpg",
    views: 856,
    featured: false,
  },
  {
    title: "Cybersecurity: Melindungi Data Pribadi di Era Digital",
    excerpt: "Tips dan strategi untuk menjaga keamanan data pribadi dalam aktivitas digital sehari-hari.",
    author: "Budi Santoso",
    authorRole: "Cybersecurity Specialist",
    date: "2024-03-10",
    readTime: "6 min read",
    category: "Cybersecurity",
    image: "/blog/cybersecurity.jpg",
    views: 642,
    featured: false,
  },
  {
    title: "Mobile Development dengan React Native: Best Practices",
    excerpt: "Kumpulan best practices dalam pengembangan aplikasi mobile menggunakan React Native untuk performa optimal.",
    author: "Rina Maharani",
    authorRole: "Mobile Developer",
    date: "2024-03-08",
    readTime: "10 min read",
    category: "Mobile Development",
    image: "/blog/react-native.jpg",
    views: 729,
    featured: false,
  },
  {
    title: "UI/UX Design: Prinsip Design Thinking untuk Developer",
    excerpt: "Memahami prinsip-prinsip design thinking yang dapat diterapkan developer dalam menciptakan user experience yang baik.",
    author: "Dian Pratama",
    authorRole: "UI/UX Designer",
    date: "2024-03-05",
    readTime: "7 min read",
    category: "UI/UX Design",
    image: "/blog/design-thinking.jpg",
    views: 583,
    featured: false,
  },
  {
    title: "Cloud Computing: Migrasi Aplikasi ke AWS",
    excerpt: "Panduan step-by-step untuk melakukan migrasi aplikasi existing ke Amazon Web Services dengan best practices.",
    author: "Eko Prasetyo",
    authorRole: "DevOps Engineer",
    date: "2024-03-02",
    readTime: "15 min read",
    category: "Cloud Computing",
    image: "/blog/aws-migration.jpg",
    views: 912,
    featured: false,
  },
  {
    title: "Data Science untuk Pemula: Analisis Data dengan Python",
    excerpt: "Pengenalan data science menggunakan Python, pandas, dan matplotlib untuk analisis data dasar.",
    author: "Sarah Wijaya",
    authorRole: "Data Scientist",
    date: "2024-02-28",
    readTime: "11 min read",
    category: "Data Science",
    image: "/blog/data-science.jpg",
    views: 1156,
    featured: false,
  },
  {
    title: "DevOps: Implementasi CI/CD dengan GitHub Actions",
    excerpt: "Tutorial implementasi Continuous Integration dan Continuous Deployment menggunakan GitHub Actions.",
    author: "Rudi Hermawan",
    authorRole: "DevOps Lead",
    date: "2024-02-25",
    readTime: "13 min read",
    category: "DevOps",
    image: "/blog/github-actions.jpg",
    views: 687,
    featured: false,
  },
  {
    title: "Blockchain Technology: Pengenalan Smart Contracts",
    excerpt: "Memahami konsep smart contracts dalam blockchain dan implementasinya menggunakan Solidity.",
    author: "Agus Setiawan",
    authorRole: "Blockchain Developer",
    date: "2024-02-22",
    readTime: "14 min read",
    category: "Blockchain",
    image: "/blog/smart-contracts.jpg",
    views: 534,
    featured: false,
  },
  {
    title: "Machine Learning: Sentiment Analysis untuk Media Sosial",
    excerpt: "Implementasi sentiment analysis menggunakan Python dan Natural Language Processing untuk analisis media sosial.",
    author: "Maya Sari",
    authorRole: "ML Engineer",
    date: "2024-02-20",
    readTime: "16 min read",
    category: "Machine Learning",
    image: "/blog/sentiment-analysis.jpg",
    views: 823,
    featured: false,
  },
];

export const categories = [
  { name: "Web Development", count: 15, color: "bg-blue-100 text-blue-700" },
  { name: "Mobile Development", count: 12, color: "bg-green-100 text-green-700" },
  { name: "AI & Machine Learning", count: 8, color: "bg-purple-100 text-purple-700" },
  { name: "UI/UX Design", count: 10, color: "bg-pink-100 text-pink-700" },
  { name: "Cybersecurity", count: 6, color: "bg-red-100 text-red-700" },
  { name: "Cloud Computing", count: 9, color: "bg-cyan-100 text-cyan-700" },
  { name: "Data Science", count: 7, color: "bg-orange-100 text-orange-700" },
  { name: "DevOps", count: 5, color: "bg-indigo-100 text-indigo-700" },
];

export const popularTags = [
  "React",
  "Next.js",
  "Python",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "React Native",
  "AI/ML",
  "Cybersecurity",
  "AWS",
  "Docker",
  "Git",
];
